# Generated by Django 6.0.2 on 2026-08-29 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_cows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cowactivity',
            name='cow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.cow'),
        ),
        migrations.AddField(
            model_name='cowactivity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farm',
            name='agent',
            field=models.ForeignKey(limit_choices_to={'role': 'agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_farms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cow',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cows', to='api.farm'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers', to='api.farm'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milkrecord',
            name='cow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='api.cow'),
        ),
        migrations.AddField(
            model_name='milkrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_milk_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
